---
- name: Transfer environment variables
  hosts: webservers
  tasks:
  - name: Copy the latest env file
    copy:
      src: /Users/yuriylemberg/Documents/apps/basketball-trivia/.env
      dest: /home/ubuntu/basketball-trivia/.env
  - name:
    git: repo=git://github.com/ylemberg/basketball-trivia.git
        dest=/home/ubuntu/basketball-trivia